# Generated by Django 6.0.6 on 2026-07-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tender",
            name="budget",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Estimated budget for the tender.",
                max_digits=12,
                null=True,
            ),
        ),
    ]
