# Generated by Django 6.0.6 on 2026-07-20 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenders", "0003_bid"),
    ]

    operations = [
        migrations.AddField(
            model_name="bid",
            name="quotation_document",
            field=models.FileField(
                blank=True,
                help_text="Uploaded quotation document.",
                null=True,
                upload_to="quotations/",
            ),
        ),
        migrations.AddField(
            model_name="tender",
            name="eligibility_criteria",
            field=models.TextField(
                blank=True, help_text="Criteria for company eligibility."
            ),
        ),
        migrations.AddField(
            model_name="tender",
            name="technical_requirements",
            field=models.TextField(
                blank=True, help_text="Technical specifications and requirements."
            ),
        ),
        migrations.AddField(
            model_name="tender",
            name="tender_document",
            field=models.FileField(
                blank=True,
                help_text="Upload a PDF document for the tender.",
                null=True,
                upload_to="tender_documents/",
            ),
        ),
        migrations.AddField(
            model_name="tender",
            name="terms_and_conditions",
            field=models.TextField(
                blank=True, help_text="All rules and regulations for this tender."
            ),
        ),
    ]
