# Generated by Django 6.0.6 on 2026-07-20 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenders", "0004_bid_quotation_document_tender_eligibility_criteria_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tender",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending_review", "Pending Review"),
                    ("pending_approval", "Pending Approval"),
                    ("approved", "Approved"),
                    ("published", "Published"),
                    ("rejected", "Rejected"),
                    ("archived", "Archived"),
                    ("expired", "Expired"),
                    ("completed", "Completed"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
