# Generated by Django 6.0.6 on 2026-07-21 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institution", "0009_delete_tender_delete_tenderactivity"),
        ("tenders", "0005_alter_tender_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bid",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="bid",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="tender",
            name="category",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="bid",
            name="cover_letter",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bid",
            name="proposal_document",
            field=models.FileField(upload_to="bid_proposals/"),
        ),
        migrations.AlterField(
            model_name="bid",
            name="quotation_document",
            field=models.FileField(blank=True, null=True, upload_to="bid_quotations/"),
        ),
        migrations.AlterField(
            model_name="tender",
            name="budget",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="tender",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_tenders",
                to="institution.institutionuser",
            ),
        ),
        migrations.AlterField(
            model_name="tender",
            name="eligibility_criteria",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tender",
            name="remarks",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tender",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending_review", "Pending Review"),
                    ("pending_approval", "Pending Approval"),
                    ("published", "Published"),
                    ("rejected", "Rejected"),
                    ("completed", "Completed"),
                    ("expired", "Expired"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="tender",
            name="technical_requirements",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tender",
            name="tender_document",
            field=models.FileField(
                blank=True, null=True, upload_to="tender_documents/"
            ),
        ),
        migrations.AlterField(
            model_name="tender",
            name="terms_and_conditions",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tenderactivity",
            name="action",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="tenderactivity",
            name="performed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="institution.institutionuser",
            ),
        ),
    ]
