# Generated by Django 6.0.6 on 2026-07-23 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenders", "0006_alter_bid_options_alter_bid_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tender",
            name="opening_date",
            field=models.DateTimeField(
                blank=True,
                help_text="If set, bidding will only be allowed on or after this date.",
                null=True,
                verbose_name="Tender Opening Date",
            ),
        ),
        migrations.AlterField(
            model_name="bid",
            name="proposal_document",
            field=models.FileField(blank=True, null=True, upload_to="PDF/proposal/"),
        ),
        migrations.AlterField(
            model_name="bid",
            name="quotation_document",
            field=models.FileField(blank=True, null=True, upload_to="PDF/quotation/"),
        ),
        migrations.AlterField(
            model_name="tender",
            name="tender_document",
            field=models.FileField(
                blank=True, null=True, upload_to="PDF/tender_documents/"
            ),
        ),
    ]
