# Generated by Django 6.0.6 on 2026-08-09 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenders", "0007_tender_opening_date_alter_bid_proposal_document_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tender",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("it", "IT & Technology"),
                    ("furniture", "Furniture & Fixtures"),
                    ("construction", "Construction & Renovation"),
                    ("stationery", "Office & School Supplies"),
                    ("services", "Professional Services"),
                    ("maintenance", "Maintenance & Repair"),
                    ("other", "Other"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
