# Generated by Django 6.0.6 on 2026-08-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenders", "0008_alter_tender_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="bid",
            name="remarks",
            field=models.TextField(
                blank=True,
                help_text="Internal remarks from company admin if a draft is rejected.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="bid",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("submitted", "Submitted"),
                    ("under_review", "Under Review"),
                    ("shortlisted", "Shortlisted"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
