# Generated by Django 6.0.6 on 2026-08-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenders", "0009_bid_remarks_alter_bid_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bid",
            name="remarks",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bid",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_approval", "Pending Approval"),
                    ("submitted", "Submitted"),
                    ("under_review", "Under Review"),
                    ("shortlisted", "Shortlisted"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                ],
                default="pending_approval",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="tender",
            name="opening_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Tender Opening Date"
            ),
        ),
    ]
