# Generated by Django 6.0.6 on 2026-07-14 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0001_initial"),
        ("institution", "0007_institutionuser_phone_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="description",
            field=models.TextField(blank=True, verbose_name="About the Company"),
        ),
        migrations.AddField(
            model_name="company",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="company_logos/",
                verbose_name="Company Logo",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="website",
            field=models.URLField(blank=True, verbose_name="Website URL"),
        ),
        migrations.AlterField(
            model_name="company",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name="Bid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bid_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("proposal_document", models.FileField(upload_to="proposals/")),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("under_review", "Under Review"),
                            ("shortlisted", "Shortlisted"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        default="submitted",
                        max_length=20,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bids",
                        to="company.company",
                    ),
                ),
                (
                    "tender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bids",
                        to="institution.tender",
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
                "unique_together": {("tender", "company")},
            },
        ),
    ]
