# Generated by Django 6.0.6 on 2026-07-15 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0002_company_description_company_profile_picture_and_more"),
        ("tenders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bid",
            name="tender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bids",
                to="tenders.tender",
            ),
        ),
    ]
