# Generated by Django 6.0.6 on 2026-07-16 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0003_alter_bid_tender"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Bid",
        ),
    ]
