# Generated by Django 6.0.6 on 2026-07-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0004_delete_bid"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="is_approved",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the company has been approved by a system admin.",
            ),
        ),
    ]
