# Generated by Django 6.0.6 on 2026-07-26 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0005_company_is_approved"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="pan_number",
            field=models.CharField(
                blank=True,
                help_text="Enter the company's PAN or VAT number.",
                max_length=20,
                verbose_name="PAN/VAT Number",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="registration_certificate",
            field=models.FileField(
                blank=True,
                help_text="Upload the official company registration certificate.",
                null=True,
                upload_to="company_verification/",
                verbose_name="Company Registration Certificate",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="registration_number",
            field=models.CharField(
                blank=True,
                help_text="Enter the official company registration number.",
                max_length=100,
                verbose_name="Registration Number",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="verification_remarks",
            field=models.TextField(
                blank=True,
                help_text="Remarks from the admin regarding verification status.",
                verbose_name="Admin Verification Remarks",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("not_submitted", "Not Submitted"),
                    ("pending", "Pending Review"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="not_submitted",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
