# Generated by Django 6.0.6 on 2026-08-09 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "company",
            "0006_company_pan_number_company_registration_certificate_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("bid_submitter", "Bid Submitter"),
                    ("viewer", "Viewer"),
                ],
                default="admin",
                help_text="Role of the user within the company.",
                max_length=20,
            ),
        ),
    ]
