# Generated by Django 6.0.6 on 2026-08-21 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0007_company_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyEntity",
            fields=[],
            options={
                "verbose_name": "Company",
                "verbose_name_plural": "Companies",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("company.company",),
        ),
        migrations.AlterModelOptions(
            name="company",
            options={
                "verbose_name": "Company User",
                "verbose_name_plural": "Company Users",
            },
        ),
    ]
