# Generated by Django 6.0.6 on 2026-09-04 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0008_companyentity_alter_company_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="phone_number",
            field=models.CharField(max_length=10),
        ),
    ]
