# Generated by Django 6.0.6 on 2026-07-06 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institution", "0002_alter_institution_email_alter_institution_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institutionuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Institution Admin"),
                    ("creator", "Creator"),
                    ("reviewer", "Reviewer"),
                ],
                default="creator",
                max_length=20,
            ),
        ),
    ]
