# Generated by Django 6.0.6 on 2026-07-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institution", "0003_alter_institutionuser_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="tender",
            name="deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tender",
            name="remarks",
            field=models.TextField(
                blank=True, help_text="Reason for rejection, if applicable.", null=True
            ),
        ),
    ]
