# Generated by Django 6.0.6 on 2026-07-11 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institution", "0004_tender_deadline_tender_remarks"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="description",
            field=models.TextField(blank=True, verbose_name="About the Institution"),
        ),
        migrations.AddField(
            model_name="institution",
            name="institution_head_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Institution Head Name"
            ),
        ),
        migrations.AddField(
            model_name="institution",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="institution_profiles/",
                verbose_name="Profile Picture",
            ),
        ),
        migrations.AddField(
            model_name="institution",
            name="website",
            field=models.URLField(blank=True, verbose_name="Website URL"),
        ),
    ]
