# Generated by Django 6.0.6 on 2026-07-11 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institution", "0006_alter_tender_status_tenderactivity"),
    ]

    operations = [
        migrations.AddField(
            model_name="institutionuser",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Phone Number"
            ),
        ),
        migrations.AddField(
            model_name="institutionuser",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="user_profiles/",
                verbose_name="Profile Picture",
            ),
        ),
    ]
