# Generated by Django 6.0.6 on 2026-07-15 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("institution", "0007_institutionuser_phone_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tender",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="tender",
            name="institution",
        ),
        migrations.RemoveField(
            model_name="tenderactivity",
            name="tender",
        ),
        migrations.RemoveField(
            model_name="tenderactivity",
            name="performed_by",
        ),
    ]
