# Generated by Django 6.0.6 on 2026-07-15 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0003_alter_bid_tender"),
        (
            "institution",
            "0008_remove_tender_created_by_remove_tender_institution_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="Tender",
        ),
        migrations.DeleteModel(
            name="TenderActivity",
        ),
    ]
