# Generated by Django 6.0.6 on 2026-07-24 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institution", "0009_delete_tender_delete_tenderactivity"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="is_approved",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the institution has been approved by a system admin.",
            ),
        ),
    ]
