# Generated by Django 6.0.6 on 2026-07-26 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institution", "0010_institution_is_approved"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="pan_number",
            field=models.CharField(
                blank=True,
                help_text="Enter the institution's PAN number.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="institution",
            name="registration_certificate",
            field=models.FileField(
                blank=True,
                help_text="Upload the official legal registration certificate.",
                null=True,
                upload_to="institution_verification/",
            ),
        ),
        migrations.AddField(
            model_name="institution",
            name="registration_number",
            field=models.CharField(
                blank=True,
                help_text="Enter the official registration number.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="institution",
            name="verification_remarks",
            field=models.TextField(
                blank=True,
                help_text="Remarks from the admin regarding verification status.",
            ),
        ),
        migrations.AddField(
            model_name="institution",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("not_submitted", "Not Submitted"),
                    ("pending", "Pending Review"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="not_submitted",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="user",
            field=models.OneToOneField(
                help_text="The admin user for this institution.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="institution_admin_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
