# Generated by Django 6.0.6 on 2026-07-26 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("institution", "0011_institution_pan_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="institution",
            name="user",
        ),
    ]
