# Generated by Django 6.0.6 on 2026-07-26 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institution", "0012_remove_institution_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="authorization_letter",
            field=models.FileField(
                blank=True,
                help_text="An official letter authorizing this account to act on behalf of the institution.",
                null=True,
                upload_to="institution_verification/",
                verbose_name="Authorization Letter (Optional)",
            ),
        ),
        migrations.AddField(
            model_name="institution",
            name="contact_person",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Contact Person Name"
            ),
        ),
        migrations.AddField(
            model_name="institution",
            name="contact_person_number",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Contact Person Number"
            ),
        ),
        migrations.AddField(
            model_name="institution",
            name="institution_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("public", "Public University/College"),
                    ("private", "Private University/College"),
                    ("government", "Government Body"),
                    ("ngo", "Non-Governmental Organization"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=50,
                verbose_name="Type of Institution",
            ),
        ),
        migrations.AddField(
            model_name="institution",
            name="pan_certificate",
            field=models.FileField(
                blank=True,
                help_text="Upload a copy of the PAN/VAT registration certificate if available.",
                null=True,
                upload_to="institution_verification/",
                verbose_name="PAN/VAT Certificate (Optional)",
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="pan_number",
            field=models.CharField(
                help_text="Enter the institution's PAN or VAT number.",
                max_length=20,
                verbose_name="PAN/VAT Number",
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="registration_certificate",
            field=models.FileField(
                help_text="Upload the official legal registration certificate.",
                upload_to="institution_verification/",
                verbose_name="Registration Certificate",
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="registration_number",
            field=models.CharField(
                help_text="Enter the official registration number.",
                max_length=100,
                verbose_name="Registration Number",
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="verification_remarks",
            field=models.TextField(
                blank=True,
                help_text="Remarks from the admin regarding verification status.",
                verbose_name="Admin Verification Remarks",
            ),
        ),
    ]
