# Generated by Django 6.0.6 on 2026-09-04 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institution", "0013_institution_authorization_letter_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institution",
            name="phone_number",
            field=models.CharField(max_length=10),
        ),
    ]
